import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import { Toaster } from "react-hot-toast";
import SessionProvider from '@/app/components/SessionProvider'
import { auth } from "@/auth"
import styles from "@/app/lib/css/backgroundColor.module.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-Commerce Clone!",
  description: "Generated by create next app",
  icons: {
    icon: ["/icon.ico"],
    apple: ["/apple-touch-icon.png"]
  }
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth()

  return (
      <html lang="en">
        <body className={`${inter.className} ${styles.background}`}>
        <SessionProvider session={session}> 
          <Toaster position="top-center" />
          <NavBar /> 
          {children} 
          </SessionProvider>
        </body>
      </html>
  );
}
